# fly.toml app configuration file generated for omition on 2023-12-13T00:04:59+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "omition"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[mounts]
  source = "data"
  destination = "/data"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3306
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "1s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false

  [[services.http_checks]]
    interval = 10000
    grace_period = "1s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
