# fly.toml app configuration file generated for foutline on 2024-01-17T10:43:51+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foutline"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3306

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "1m0s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"

  [[services.http_checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthcheck"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024
